include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm1284a_hd720_dsi_vdo_boe")
obj-y   +=  otm1284a_hd720_dsi_vdo_boe.o
endif

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"otm1284a_hd720_dsi_vdo_tianma")
obj-y   +=  otm1284a_hd720_dsi_vdo_tianma.o
endif
